const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  pickInputFile: () => ipcRenderer.invoke('pick-input-file'),
  pickOutputLocation: (defaultName) => ipcRenderer.invoke('pick-output-location', defaultName),
  getTeamList: () => ipcRenderer.invoke('get-team-list'),
  getRegularBowls: () => ipcRenderer.invoke('get-regular-bowls'),
  getTeamConferences: () => ipcRenderer.invoke('get-team-conferences'),
  detectConferenceChampions: (payload) => ipcRenderer.invoke('detect-conference-champions', payload),
  computeBcsRankings: (payload) => ipcRenderer.invoke('compute-bcs-rankings', payload),
  getRound1Status: (payload) => ipcRenderer.invoke('get-round1-status', payload),
  getRound1Status12: (payload) => ipcRenderer.invoke('get-round1-status-12', payload),
  detectConferencesFromSchedule: (payload) => ipcRenderer.invoke('detect-conferences-from-schedule', payload),
  saveConferenceOverrides: (payload) => ipcRenderer.invoke('save-conference-overrides', payload),
  checkConferenceOverridesExist: () => ipcRenderer.invoke('check-conference-overrides-exist'),
  checkConferenceMismatch: (payload) => ipcRenderer.invoke('check-conference-mismatch', payload),
  runEdit: (payload) => ipcRenderer.invoke('run-edit', payload),
  protectUserCoach: (payload) => ipcRenderer.invoke('protect-user-coach', payload),
  checkUserCoach: (payload) => ipcRenderer.invoke('check-user-coach', payload),
  verifyGameFingerprint: (payload) => ipcRenderer.invoke('verify-game-fingerprint', payload),
  getBracketState: (args) => ipcRenderer.invoke('get-bracket-state', args),
  getTeamColors: () => ipcRenderer.invoke('get-team-colors'),
  getBracketHistory: () => ipcRenderer.invoke('get-bracket-history'),
  saveBracketToHistory: (payload) => ipcRenderer.invoke('save-bracket-to-history', payload),
});
